name: windows-build
on:
  push:
    branches:
      - 'win'  # only default branch
  pull_request:

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    name: ${{ matrix.compiler }}
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    steps:
      - uses: actions/checkout@v3
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.9
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      - name: Process pending sql
        shell: bash
        run: bash bin/acore-db-pendings
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=maps-only
          export CCONTINUOUS_INTEGRATION=ON
          ./acore.sh compiler build
      - name: Copy dll files
        shell: bash
        run: |
          cp "/c/Program Files/OpenSSL/bin/legacy.dll" "env/dist"
      - name: Dry run authserver
        shell: bash
        run: |
          source ./apps/ci/ci-gen-server-conf-files.sh "authserver" "configs" "."
          cd env/dist
          ./authserver -dry-run
      - name: Dry run worldserver
        shell: bash
        run: |
          source ./apps/ci/ci-gen-server-conf-files.sh "worldserver" "configs" "."
          cd env/dist
          ./worldserver -dry-run
      - name: Stop MySQL
        run: net stop mysql
